//! This module handles the server-side of the OPAQUE login process.

use crate::common::{DefaultCipherSuite, RegistrationError};
use opaque_ke::{RegistrationRequest, RegistrationUpload, ServerRegistration, ServerSetup};

/// The first sep of the OPAQUE login flow on the server side.
///
/// This function takes a previously generated server setup,
/// a RegistrationRequest generated by the client,
/// and the client's ID.
/// It returns a RegistrationResponse to be returned to the client.
#[uniffi::export]
pub fn server_registration_start(
    server_setup: Vec<u8>,
    registration_request: Vec<u8>,
    client_id: &[u8],
) -> Result<Vec<u8>, RegistrationError> {
    let server_setup_obj = ServerSetup::<DefaultCipherSuite>::deserialize(&server_setup)
        .map_err(|e| RegistrationError::Generic(format!("{:?}", e)))?;

    let registration_request_obj =
        RegistrationRequest::<DefaultCipherSuite>::deserialize(&registration_request)
            .map_err(|e| RegistrationError::Generic(format!("{:?}", e)))?;

    let server_result = ServerRegistration::<DefaultCipherSuite>::start(
        &server_setup_obj,
        registration_request_obj,
        client_id,
    )
    .map_err(|e| RegistrationError::Generic(format!("{:?}", e)))?;

    Ok(server_result.message.serialize().to_vec())
}

/// Completes the QPAQUE login flow on the server side.
///
/// Takes a RegistrationUpload from the client and returns a password file to be stored server side
#[uniffi::export]
pub fn server_registration_finish(
    registration_upload: Vec<u8>,
) -> Result<Vec<u8>, RegistrationError> {
    let reg_upload = RegistrationUpload::<DefaultCipherSuite>::deserialize(&registration_upload)
        .map_err(|e| RegistrationError::Generic(format!("{:?}", e)))?;

    let password_file = ServerRegistration::<DefaultCipherSuite>::finish(reg_upload);
    Ok(password_file.serialize().to_vec())
}
